# Form implementation generated from reading ui file 'hata.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hata(object):
    def setupUi(self, hata):
        hata.setObjectName("hata")
        hata.resize(615, 246)
        hata.setStyleSheet("background-color: rgb(37, 38, 39);")
        hata.setWindowIcon(QtGui.QIcon("data/icon.ico"))
        self.gridLayout = QtWidgets.QGridLayout(hata)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=hata)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(100, -1, 100, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=hata)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(191, 180, 143);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=hata)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(200, -1, 200, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ButtonKapat = QtWidgets.QPushButton(parent=self.widget_2)
        self.ButtonKapat.setStyleSheet("background-color: rgb(242, 239, 233);")
        self.ButtonKapat.setObjectName("ButtonKapat")
        self.verticalLayout_2.addWidget(self.ButtonKapat)
        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 2)

        self.retranslateUi(hata)
        QtCore.QMetaObject.connectSlotsByName(hata)

    def retranslateUi(self, hata):
        _translate = QtCore.QCoreApplication.translate
        hata.setWindowTitle(_translate("hata", "Sözlük App"))
        self.label_2.setText(_translate("hata", "1234erytuyjghfds"))
        self.label.setText(_translate("hata", "HATA"))
        self.ButtonKapat.setText(_translate("hata", "Tamam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hata = QtWidgets.QWidget()
    ui = Ui_hata()
    ui.setupUi(hata)
    hata.show()
    sys.exit(app.exec())
